docs/pages/Configuration.md
packages/ui5-cc-excelUpload-Button/ExcelUpload.js
packages/ui5-cc-excelUpload/src/Component.gen.d.ts
packages/ui5-cc-excelUpload/src/Component.ts
packages/ui5-cc-excelUpload/src/controller/ErrorHandler.ts
packages/ui5-cc-excelUpload/src/controller/ExcelUpload.ts
packages/ui5-cc-excelUpload/src/controller/Parser.ts
packages/ui5-cc-excelUpload/src/controller/Util.ts

This reverts commit 4346e1bb00473363167b0d24c8ebf14e40b073cb.

Revert "feat!: removal of option `fieldMatchType` (#157)"

---

packages/ui5-cc-excelUpload/src/Component.ts
packages/ui5-cc-excelUpload/src/control/ExcelDialog.ts
packages/ui5-cc-excelUpload/src/controller/ExcelUpload.ts
packages/ui5-cc-excelUpload/src/controller/MessageHandler.ts
packages/ui5-cc-excelUpload/src/controller/SheetHandler.ts
packages/ui5-cc-excelUpload/src/controller/dialog/ExcelUploadDialog.ts
packages/ui5-cc-excelUpload/src/controller/odata/MetadataHandlerV4.ts
packages/ui5-cc-excelUpload/src/controller/odata/OData.ts
packages/ui5-cc-excelUpload/src/controller/odata/ODataV2.ts
packages/ui5-cc-excelUpload/src/controller/odata/ODataV4.ts
packages/ui5-cc-excelUpload/src/types.ts
tsconfig.json

chore: ts update

---

docs/pages/GettingStarted.md
examples/packages/ordersv2freestylenondraft/webapp/view/Detail.view.xml
examples/packages/ordersv2freestylenondraft/webapp/view/List.view.xml
examples/packages/ordersv2freestylenondraft/webapp/view/UploadToTable.view.xml
examples/packages/ordersv2freestylenondraftopenui5/webapp/view/Detail.view.xml
examples/packages/ordersv4fe/webapp/custom/fragment/OrderItems.fragment.xml
examples/packages/ordersv4fe/webapp/ext/controller/OrderItems.controller.js
examples/packages/ordersv4fe/webapp/manifest.json
examples/packages/ordersv4fpm/webapp/ext/main/Main.view.xml
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV4.ts

fix: enable usage of controller extensions

---

packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts

fix: close busy dialog on backend error

---

packages/ui5-cc-spreadsheetimporter/src/controller/Preview.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts

fix: use label in preview table

---

packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV2.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV4.ts

fix: check for odata type config parameter

---

packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts

fix: template generation in standalone mode

---

docs/pages/Configuration.md
examples/packages/ordersv4fe/webapp/ext/ListReportExtController.js
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_de.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_en.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_es.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_fr.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_hi.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_it.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_ja.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_zh.properties
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

feat: add sheet selector if multiple sheets in file

---

docs/pages/Events.md
docs/pages/GettingStarted.md
examples/packages/ordersv2fe/webapp/ext/controller/ListReportExt.controller.js
examples/packages/ordersv2fe/webapp/ext/controller/ObjectPageExt.controller.js
examples/packages/ordersv4fe/webapp/ext/ListReportExtController.js
examples/packages/ordersv4fe/webapp/ext/ObjectPageExtController.js
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts

feat: new event `requestCompleted`

---

packages/ui5-cc-spreadsheetimporter/src/Component.ts

fix: add missing event requestCompleted to eventMethodMap

---

docs/index.md
docs/pages/Button.md
docs/pages/Configuration.md
docs/pages/GettingStarted.md
docs/pages/SupportVersions.md

docs: remove info for deprecated ui5 cli v2

---

packages/ui5-cc-spreadsheetimporter/src/fragment/SpreadsheetUpload.fragment.xml

fix: add xlsm add upload type

---

docs/pages/Configuration.md
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Util.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

feat: new config to provide own template file

---

docs/pages/Events.md
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts

fix: add parsedData to CheckBeforeRead event

---

docs/pages/GettingStarted.md

docs: update information for deployment

---

packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/fragment/SpreadsheetUpload.fragment.xml

fix: hide generateTemplate in standalone

---

packages/ui5-cc-spreadsheetimporter/src/controller/dialog/ODataMessageHandler.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts

fix: better error handling on backend errors

---

docs/pages/Configuration.md
examples/packages/ordersv4fe/webapp/ext/ListReportExtController.js
examples/packages/server/db/schema.cds
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Parser.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/MetadataHandlerV4.ts
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

feat: new config to send the spreadsheet row to the backend

---

docs/pages/Configuration.md
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Preview.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

feat: new config to define columns in preview

---

docs/pages/Checks.md
docs/pages/Configuration.md
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/MessageHandler.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/enums.ts
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_de.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_en.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_es.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_fr.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_hi.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_it.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_ja.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_zh.properties
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

feat: new checks for maxLength and duplicate columns

---

docs/pages/Configuration.md
examples/packages/ordersv4fe/webapp/ext/ListReportExtController.js
examples/packages/server/httprequests/OrdersPOST.http
examples/packages/server/package.json
examples/packages/server/srv/orders-service.js
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts
packages/ui5-cc-spreadsheetimporter/src/types.d.ts
pnpm-lock.yaml

feat: create active data

---

packages/ui5-cc-spreadsheetimporter/src/controller/Parser.ts

fix: string assignment using nullish coalescing operator

---

.github/ISSUE_TEMPLATE/bug.yml

chore: improve issue template

---

docs/pages/Events.md
packages/ui5-cc-spreadsheetimporter/src/controller/Util.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts

fix: preventDefault on event `uploadButtonPress`

---

docs/pages/Events.md
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts

fix: show error in standalone mode after upload button press

---

docs/pages/GettingStarted.md

docs: fix version

---

packages/ui5-cc-spreadsheetimporter/src/controller/Parser.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Util.ts

fix: make sure Edm.Date uses the correct date

---

packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Preview.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/MetadataHandler.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/MetadataHandlerV2.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV2.ts

refactor: get rid of hungarian notation

---

packages/ui5-cc-spreadsheetimporter/src/controller/MessageHandler.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/fragment/MessagesDialog.fragment.xml

fix: turn off `continue anyway` on error dialog after upload button press

---

packages/ui5-cc-spreadsheetimporter/src/control/SpreadsheetDialog.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/control/SpreadsheetDialog.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/css/style.css
packages/ui5-cc-spreadsheetimporter/src/fragment/SpreadsheetUpload.fragment.xml
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_de.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_en.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_es.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_fr.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_hi.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_it.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_ja.properties
packages/ui5-cc-spreadsheetimporter/src/i18n/i18n_zh.properties

feat: add drag&drop to dialog

---

.github/ISSUE_TEMPLATE/feature.yml

chore: add feature issue template

---

packages/ui5-cc-spreadsheetimporter/src/controller/Parser.ts

fix: parse Edm.Byte and Edm.SByte

---

packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts

fix: reset context on server error

---

docs/pages/Configuration.md
docs/pages/Events.md
docs/pages/GettingStarted.md
docs/pages/TableSelector.md
docs/pages/Typescript.md
examples/packages/ordersv2fe/webapp/ext/controller/ListReportExt.controller.js
examples/packages/ordersv2fe/webapp/ext/controller/ObjectPageExt.controller.js
examples/packages/ordersv2fenondraft/webapp/ext/controller/ListReportExt.controller.js
examples/packages/ordersv2fenondraft/webapp/ext/controller/ObjectPageExt.controller.js
examples/packages/ordersv2freestylenondraft/webapp/controller/Detail.controller.js
examples/packages/ordersv2freestylenondraft/webapp/controller/List.controller.js
examples/packages/ordersv2freestylenondraft/webapp/controller/UploadToTable.controller.js
examples/packages/ordersv2freestylenondraft2/webapp/controller/Detail.controller.js
examples/packages/ordersv2freestylenondraft2/webapp/controller/List.controller.js
examples/packages/ordersv2freestylenondraft2/webapp/controller/UploadToTable.controller.js
examples/packages/ordersv2freestylenondraftopenui5/webapp/controller/Detail.controller.js
examples/packages/ordersv2freestylenondraftopenui5/webapp/controller/List.controller.js
examples/packages/ordersv4fe/webapp/ext/ListReportExtController.js
examples/packages/ordersv4fe/webapp/ext/ObjectPageExtController.js
examples/packages/ordersv4fets/webapp/ext/ListReportExtController.ts
examples/packages/ordersv4fets/webapp/ext/ObjectPageExtController.ts
examples/packages/ordersv4fpm/webapp/ext/main/Main.controller.js
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Util.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

fix #514 
- for event `changeBeforeCreate` just return the payload to change it
- method `setPayload`removed (did not work anyway)
- updated docs
- updated sample apps

fix: make sure payload in `changeBeforeCreate` is used

---

docs/pages/GettingStarted.md

docs: update component information

---

dev/replace-string.js
dev/update-version-docs.js
dev/util.js
docs/pages/Button.md
docs/pages/GettingStarted.md
docs/pages/Troubleshooting.md
docs/pages/Typescript.md
examples/packages/ordersv2fe/webapp/manifest.json
examples/packages/ordersv2fenondraft/webapp/manifest.json
examples/packages/ordersv2freestylenondraft/webapp/manifest.json
examples/packages/ordersv2freestylenondraft2/webapp/manifest.json
examples/packages/ordersv2freestylenondraftopenui5/webapp/manifest.json
examples/packages/ordersv4fe/webapp/manifest.json
examples/packages/ordersv4fets/webapp/manifest.json
examples/packages/ordersv4fpm/webapp/manifest.json
examples/packages/server/app/launchpad.html
packages/ui5-cc-spreadsheetimporter-generator/generators/app/index.js
packages/ui5-cc-spreadsheetimporter/ui5-serve.yaml
packages/ui5-cc-spreadsheetimporter/ui5.yaml

feat!: enable packaged deployment 

---

docs/pages/Button.md
docs/pages/GettingStarted.md
docs/pages/Troubleshooting.md
docs/pages/Typescript.md
examples/test/specs/all/UploadFileObjectPage.test.js
examples/test/specs/all/UploadFileObjectPageCSV.test.js
packages/ui5-cc-spreadsheetimporter/src/controller/Parser.ts

fix: add seconds when parsing odata time

---

dev/replace-string.js
dev/util.js
packages/ui5-cc-spreadsheetimporter/src/manifest.json

chore: update `applicationVersion` in manifest on version change

---

packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts
packages/ui5-cc-spreadsheetimporter/src/fragment/SpreadsheetUpload.fragment.xml

fix: dialog margin in `sapUiSizeCozy` mode

---

docs/index.md
docs/pages/CentralDeployment.md
docs/pages/Configuration.md
docs/pages/Development/SampleApps.md
docs/pages/GettingStarted.md
docs/pages/SupportVersions.md
mkdocs.yml

docs: new central abap deployment concept

---

docs/pages/APIReference.md
mkdocs.yml

docs: add api reference

---

docs/pages/GettingStarted.md

docs: how to use central component in dev env

---

docs/pages/GettingStarted.md

docs: ts files added to deployment

---

docs/pages/CentralDeployment.md

docs: add specific instructions for deploying to public cloud

---

docs/pages/CentralDeployment.md
docs/pages/GettingStarted.md

docs: use the app with central deployed component

---

docs/pages/CentralDeployment.md
docs/pages/GettingStarted.md

docs: reference to `cds-plugin-ui5`

---

packages/ui5-cc-spreadsheetimporter/src/controller/Parser.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/MetadataHandlerV4.ts
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

fix: `Edm.DateTimeOffset` parsing with and without precision

---

packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts

fix: force refresh only for v2 and when refresh failed

---

.gitignore
docs/pages/Configuration.md
examples/packages/ordersv4fe/webapp/ext/ListReportExtController.js
packages/ui5-cc-spreadsheetimporter/src/Component.gen.d.ts
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV2.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV4.ts
packages/ui5-cc-spreadsheetimporter/src/fragment/BusyDialogProgress.fragment.xml
packages/ui5-cc-spreadsheetimporter/src/types.d.ts

with this new parameter it is possible to use the upload without a table, just provide a OData Binding
TODO:

feat: new parameter `bindingCustom`

---

packages/ui5-cc-spreadsheetimporter/src/controller/dialog/SpreadsheetUploadDialog.ts

Support OData V4 for freestyle

fix: in V4 context check if it is possible to execute with `editFlow`

---

packages/ui5-cc-spreadsheetimporter/src/controller/Preview.ts

fix: preview did not show all columns

---

.github/workflows/wdi5-test.yml
examples/.gitignore
examples/package.json
examples/packages/server/db/schema.cds
examples/packages/server/package.json
examples/test/wdio-base.conf.js
pnpm-lock.yaml

chore: add wdio timeline reporter and upload to workflow

---

packages/ui5-cc-spreadsheetimporter/src/controller/odata/MetadataHandlerV2.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/MetadataHandlerV4.ts

fix: make the search by property label more resilient

---

packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV4RequestObjects.ts

fix: handle process if object was not found in backend

---

.github/workflows/opa5-test.yml
.github/workflows/wdi5-test.yml
docs/pages/GettingStarted.md
examples/Dockerfile
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/Util.ts

fix: check configuration options if valid

---

packages/ui5-cc-spreadsheetimporter/src/controller/TableSelector.ts
packages/ui5-cc-spreadsheetimporter/src/controller/odata/OData.ts

fix: return error if wrong table type is specified

---

docs/pages/APIReference.md
packages/ui5-cc-spreadsheetimporter/src/Component.ts
packages/ui5-cc-spreadsheetimporter/src/controller/SpreadsheetUpload.ts

feat: add new api setArrayMessages

---

docs/pages/Configuration.md

docs: add information which parameter do not work in standalone

---

packages/ui5-cc-spreadsheetimporter/src/controller/odata/ODataV4RequestObjects.ts

fix: fail if object was not found in backend
